sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # encrypt file
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project noisy-nail-23334
  - gcloud config set compute/zone asia-south1
  - gcloud container clusters get-credentials k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t suhailibnnisar/react-test -f ./client/Dockerfile.env ./client

script:
  - docker run suhailibnnisar/react-test npm run test:ci

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
