apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: suhailibnnisar/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.html": .
        "**/*.css": .
        "**/*.js": .
    - image: suhailibnnisar/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
    - image: suhailibnnisar/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yml
      - k8s/client-deployment.yml
      - k8s/client-deployment.yml
      - k8s/client-cluster-ip-service.yml
      - k8s/server-cluster-ip-service.yml
